name: CI
on: [ push, pull_request ]
jobs:
  test:
    name: test (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17' ] # We want to test on LTSs.
    steps:
      - name: actions/setup-java@v3 (JDK ${{ matrix.java }})
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          architecture: x64
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./gradlew build
